[tool.poetry]
name = "trabalho-grafos"
version = "0.1.0"
description = ""
authors = ["rodri <25470856+drigohhh@users.noreply.github.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
PyQt5 = "5.15.11"
PyQt5-Qt5 = "5.15.2"
googlemaps = "^4.10.0"
folium = "^0.19.7"
pandas = "^2.3.0"
PyQtWebEngine = "5.15.6"
PyQtWebEngine-Qt5 = "5.15.2"
python-dotenv = "^1.1.0"
matplotlib = "^3.10.3"
networkx = "^3.5"
shapely = "^2.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
